#!/bin/sh
# Run this script using instance and command parameters:
#
# ```shell
# scripts/cloud cpu start
# ```

source ./scripts/instance.sh

instance_type=$1
command_type=$2

case $instance_type in
  cpu)
    case $command_type in
      create)
        create_cpu_instance
        ;;
      status)
        cpu_instance_status
        ;;
      start)
        start_cpu_instance
        ;;
      stop)
        stop_cpu_instance
        ;;
      *)
        echo "Unknown command $command_type"
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Unknown instance $instance_type"
    exit 1
    ;;
esac
