#!/bin/sh
# Run this script using instance and command parameters:
#
# ```shell
# scripts/cloud cpu start
# ```

source ./scripts/config.sh
source ./scripts/firewall.sh
source ./scripts/instance.sh
source ./scripts/install.sh

instance_type=$1
command_type=$2

case $instance_type in
  cpu)
    case $command_type in
      status)
        cpu_instance_status
        ;;
      create)
        create_cpu_instance
        ;;
      start)
        start_cpu_instance
        ;;
      stop)
        stop_cpu_instance
        ;;
      delete)
        delete_cpu_instance
        ;;
      ssh)
        ssh_cpu_instance
        ;;
      reinstall)
        cpu_initial_install
        ;;
      *)
        echo "Unknown command $command_type"
        exit 1
        ;;
    esac
    ;;
  gpu)
    case $command_type in
      status)
        gpu_instance_status
        ;;
      create)
        create_gpu_instance
        ;;
      start)
        start_gpu_instance
        ;;
      stop)
        stop_gpu_instance
        ;;
      delete)
        delete_gpu_instance
        ;;
      ssh)
        ssh_gpu_instance
        ;;
      reinstall)
        gpu_initial_install
        ;;
      *)
        echo "Unknown command $command_type"
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Unknown instance $instance_type"
    exit 1
    ;;
esac
